### ISSUE TITLE
Cant rejoin server after leaving in mod dimensions

### ISSUE THREAD

**Issue by hellwolf95** [bartimaeusnek/BetterVoidWorlds#5] opened 2019-06-06 04:33 UTC
so im playing on a modpack and decided to add your mod onto it. on further playing i noticed when i left in another mod dimension i could not rejoin the server as it would crash [crash report](https://paste.dimdev.org/ujatoviwul.rb). upon deleting this mod i can leave and rejoin fine though so not sure what the problem really is.

**Comment by bartimaeusnek** [comment] 2019-06-07 04:32
this is most likely a problem caused by "electroblob.wizardry", can you report it there please?

**Comment by bartimaeusnek** [comment] 2019-06-13 02:24
since i gotten a response in a week ill close this

**Closed as completed by bartimaeusnek** 2019-06-13 02:24 UTC
